version: '2'
services:
  base:
    image: ncodefresh/base:master
    volumes:
      - .:/var/www

  php:
    image: ncodefresh/php
    links:
      - mysql

  phpdev:
    image: ncodefresh/phpdev
    volumes_from:
      - base
    links:
      - mysql
      - seleniumhub
    environment:
      ENVIRONMENT: Development
    ports:
      - "2023:22"
      - "8000:8000"

  phpfpm:
    image: ncodefresh/phpfpm
    volumes_from:
      - base
    links:
      - mysql

  nginx:
    image: ncodefresh/nginx
    links:
      - phpdev:php
    ports:
      - "80:80"
    volumes_from:
      - base

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app

  seleniumhub:
    image: selenium/hub

  seleniumfirefox:
    image: selenium/node-firefox
    links:
      - seleniumhub:hub
      - nginx
